version: '3.8'

services:
  synkrosphere:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: synkrosphere:latest
    container_name: synkrosphere
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8000:8000"  # Web UI
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python3 src/main.py

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.1
    container_name: synkrosphere-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
